# Generated by Django 3.2 on 2022-09-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventticket',
            options={'ordering': ['date']},
        ),
    ]
