# Generated by Django 3.2 on 2022-09-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name_plural': 'Event categories'},
        ),
    ]
